# Generated by Django 3.2.18 on 2023-02-22 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientsrecipes',
            old_name='name',
            new_name='ingredient',
        ),
    ]
