# Generated by Django 3.2.18 on 2023-02-22 20:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_auto_20230222_2226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shoppinglist',
            new_name='ShoppingCart',
        ),
    ]
